"""source id fixes added

Revision ID: 000a46b32a43
Revises: 6a026a3f3ba4
Create Date: 2025-11-04 15:07:48.878854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000a46b32a43'
down_revision: Union[str, None] = '6a026a3f3ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('source_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_attachments_source_id'), 'attachments', ['source_id'], unique=False)
    op.drop_constraint(op.f('attachments_email_id_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attachments', 'email_id')
    op.add_column('emails', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_emails_source_id'), 'emails', ['source_id'], unique=False)
    op.create_foreign_key(None, 'emails', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_expenses_processed_email_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_source_id'), 'expenses', ['source_id'], unique=False)
    op.drop_constraint(op.f('expenses_processed_email_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_column('expenses', 'processed_email_id')
    op.drop_constraint(op.f('integration_status_user_id_fkey'), 'integration_status', type_='foreignkey')
    op.add_column('processed_email_data', sa.Column('source_id', sa.Integer(), nullable=False))
    op.alter_column('processed_email_data', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_processed_email_data_source_id'), 'processed_email_data', ['source_id'], unique=False)
    op.create_foreign_key(None, 'processed_email_data', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_email_data', type_='foreignkey')
    op.drop_index(op.f('ix_processed_email_data_source_id'), table_name='processed_email_data')
    op.alter_column('processed_email_data', 'email_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('processed_email_data', 'source_id')
    op.create_foreign_key(op.f('integration_status_user_id_fkey'), 'integration_status', 'users', ['user_id'], ['id'])
    op.add_column('expenses', sa.Column('processed_email_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_processed_email_id_fkey'), 'expenses', 'processed_email_data', ['processed_email_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_expenses_source_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_processed_email_id'), 'expenses', ['processed_email_id'], unique=False)
    op.drop_column('expenses', 'source_id')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_index(op.f('ix_emails_source_id'), table_name='emails')
    op.drop_column('emails', 'source_id')
    op.add_column('attachments', sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_email_id_fkey'), 'attachments', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attachments_source_id'), table_name='attachments')
    op.drop_column('attachments', 'source_id')
    # ### end Alembic commands ###
