"""added is_proccesed colun in emails

Revision ID: 10a828247997
Revises: 66aa15d2339b
Create Date: 2025-10-28 23:26:18.464176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a828247997'
down_revision: Union[str, None] = '66aa15d2339b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.create_unique_constraint('unique_user_integration', 'integration_status', ['user_id', 'integration_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_integration', 'integration_status', type_='unique')
    op.drop_column('emails', 'is_processed')
    # ### end Alembic commands ###
