"""Fix: IntegrationFeature table and MasterIntegration table added

Revision ID: 13b6bf78bdb6
Revises: ecffe1abae30
Create Date: 2025-10-31 13:20:18.932422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b6bf78bdb6'
down_revision: Union[str, None] = 'ecffe1abae30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_status', sa.Column('integration_master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'integration_status', 'integrations', ['integration_master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integration_status', type_='foreignkey')
    op.drop_column('integration_status', 'integration_master_id')
    # ### end Alembic commands ###
