"""adding user_id column in attachements

Revision ID: 19454da54f90
Revises: 3ac6e9c3ef84
Create Date: 2025-11-07 12:47:51.331923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19454da54f90'
down_revision: Union[str, None] = '3ac6e9c3ef84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_attachments_hash'), table_name='attachments')
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_index(op.f('idx_attachments_hash'), 'attachments', ['file_hash'], unique=False)
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
