"""attachment id removed from maunal

Revision ID: 1cfec1023f34
Revises: f442502867b1
Create Date: 2025-11-07 00:32:44.281428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfec1023f34'
down_revision: Union[str, None] = 'f442502867b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_uploads_attachment_id'), table_name='manual_uploads')
    op.drop_constraint(op.f('unique_user_attachment_upload'), 'manual_uploads', type_='unique')
    op.drop_constraint(op.f('manual_uploads_attachment_id_fkey'), 'manual_uploads', type_='foreignkey')
    op.drop_column('manual_uploads', 'attachment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_uploads', sa.Column('attachment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('manual_uploads_attachment_id_fkey'), 'manual_uploads', 'attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('unique_user_attachment_upload'), 'manual_uploads', ['user_id', 'attachment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_manual_uploads_attachment_id'), 'manual_uploads', ['attachment_id'], unique=False)
    # ### end Alembic commands ###
