"""Docment staging table added

Revision ID: 20b322d3a700
Revises: 2f2c5599db59
Create Date: 2025-12-06 23:29:39.457774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20b322d3a700'
down_revision: Union[str, None] = '2f2c5599db59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_staging', sa.Column('document_processing_status', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_document_staging_processing_status'), table_name='document_staging')
    op.drop_index(op.f('idx_staging_priority_status'), table_name='document_staging')
    op.create_index('idx_staging_priority_status', 'document_staging', ['priority', 'document_processing_status', 'created_at'], unique=False)
    op.drop_index(op.f('idx_staging_status_created'), table_name='document_staging')
    op.create_index('idx_staging_status_created', 'document_staging', ['document_processing_status', 'created_at'], unique=False)
    op.drop_index(op.f('idx_staging_user_status'), table_name='document_staging')
    op.create_index('idx_staging_user_status', 'document_staging', ['user_id', 'document_processing_status'], unique=False)
    op.create_index(op.f('ix_document_staging_document_processing_status'), 'document_staging', ['document_processing_status'], unique=False)
    op.drop_column('document_staging', 'processing_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_staging', sa.Column('processing_status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_document_staging_document_processing_status'), table_name='document_staging')
    op.drop_index('idx_staging_user_status', table_name='document_staging')
    op.create_index(op.f('idx_staging_user_status'), 'document_staging', ['user_id', 'processing_status'], unique=False)
    op.drop_index('idx_staging_status_created', table_name='document_staging')
    op.create_index(op.f('idx_staging_status_created'), 'document_staging', ['processing_status', 'created_at'], unique=False)
    op.drop_index('idx_staging_priority_status', table_name='document_staging')
    op.create_index(op.f('idx_staging_priority_status'), 'document_staging', ['priority', 'processing_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_staging_processing_status'), 'document_staging', ['processing_status'], unique=False)
    op.drop_column('document_staging', 'document_processing_status')
    # ### end Alembic commands ###
