"""Integreation table, EmailConfig table, GmailConfig table

Revision ID: 386dffad2d3e
Revises: 4626de35dab4
Create Date: 2025-10-15 02:00:18.022973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386dffad2d3e'
down_revision: Union[str, None] = '4626de35dab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
