"""fix: hash column added in attachment

Revision ID: 3ac6e9c3ef84
Revises: 1cfec1023f34
Create Date: 2025-11-07 12:06:24.056986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac6e9c3ef84'
down_revision: Union[str, None] = '1cfec1023f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index('idx_attachments_hash', 'attachments', ['file_hash'], unique=False)
    op.create_index(op.f('ix_attachments_file_hash'), 'attachments', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_file_hash'), table_name='attachments')
    op.drop_index('idx_attachments_hash', table_name='attachments')
    op.drop_column('attachments', 'file_hash')
    # ### end Alembic commands ###
