"""fix: updated the user column in integreation status

Revision ID: 66aa15d2339b
Revises: 386dffad2d3e
Create Date: 2025-10-15 13:37:53.718932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66aa15d2339b'
down_revision: Union[str, None] = '386dffad2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.alter_column(
        'integration_status',
        'user_id',
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False
    )
    op.create_foreign_key(
        None,
        'integration_status',
        'users',
        ['user_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_constraint(None, 'integration_status', type_='foreignkey')
    op.alter_column(
        'integration_status',
        'user_id',
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False
    )