"""models restructued and refactor

Revision ID: 6a026a3f3ba4
Revises: 13b6bf78bdb6
Create Date: 2025-11-02 19:32:32.239110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a026a3f3ba4'
down_revision: Union[str, None] = '13b6bf78bdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_email_id_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    op.alter_column('email_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('email_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('emails_user_id_fkey'), 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.create_index('idx_expenses_user_created', 'expenses', ['user_id', 'created_at'], unique=False)
    op.alter_column('integration_status', 'integration_master_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('integration_status_integration_master_id_fkey'), 'integration_status', type_='foreignkey')
    op.drop_constraint(op.f('integration_status_user_id_fkey1'), 'integration_status', type_='foreignkey')
    op.create_foreign_key(None, 'integration_status', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'integration_status', 'integrations', ['integration_master_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('processed_email_data_user_id_fkey'), 'processed_email_data', type_='foreignkey')
    op.drop_constraint(op.f('processed_email_data_email_id_fkey'), 'processed_email_data', type_='foreignkey')
    op.create_foreign_key(None, 'processed_email_data', 'emails', ['email_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'processed_email_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscriptions_plan_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('user_tokens_user_id_fkey'), 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('whatsapp_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('whatsapp_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('whatsapp_config', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('user_tokens_user_id_fkey'), 'user_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_plan_id_fkey'), 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'processed_email_data', type_='foreignkey')
    op.drop_constraint(None, 'processed_email_data', type_='foreignkey')
    op.create_foreign_key(op.f('processed_email_data_email_id_fkey'), 'processed_email_data', 'emails', ['email_id'], ['id'])
    op.create_foreign_key(op.f('processed_email_data_user_id_fkey'), 'processed_email_data', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'integration_status', type_='foreignkey')
    op.drop_constraint(None, 'integration_status', type_='foreignkey')
    op.create_foreign_key(op.f('integration_status_user_id_fkey1'), 'integration_status', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('integration_status_integration_master_id_fkey'), 'integration_status', 'integrations', ['integration_master_id'], ['id'])
    op.alter_column('integration_status', 'integration_master_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_expenses_user_created', table_name='expenses')
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('idx_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key(op.f('emails_user_id_fkey'), 'emails', 'users', ['user_id'], ['id'])
    op.alter_column('email_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('email_config', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_email_id_fkey'), 'attachments', 'emails', ['email_id'], ['id'])
    # ### end Alembic commands ###
