"""fix: alembic changes

Revision ID: 7dc4fdff77db
Revises: b1e9fbff4f5c
Create Date: 2025-11-06 23:47:00.552022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc4fdff77db'
down_revision: Union[str, None] = 'b1e9fbff4f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_manual_uploads_processed'), table_name='manual_uploads')
    op.drop_index(op.f('idx_manual_uploads_user_status'), table_name='manual_uploads')
    op.drop_index(op.f('ix_manual_uploads_deleted_at'), table_name='manual_uploads')
    op.drop_index(op.f('ix_manual_uploads_is_processed'), table_name='manual_uploads')
    op.drop_index(op.f('ix_manual_uploads_source_id'), table_name='manual_uploads')
    op.drop_constraint(op.f('manual_uploads_source_id_fkey'), 'manual_uploads', type_='foreignkey')
    op.drop_column('manual_uploads', 'processing_status')
    op.drop_column('manual_uploads', 'display_name')
    op.drop_column('manual_uploads', 'client_metadata')
    op.drop_column('manual_uploads', 'processed_at')
    op.drop_column('manual_uploads', 'is_processed')
    op.drop_column('manual_uploads', 'currency')
    op.drop_column('manual_uploads', 'source_id')
    op.drop_column('manual_uploads', 'vendor_name')
    op.drop_column('manual_uploads', 'estimated_amount')
    op.drop_column('manual_uploads', 'deleted_at')
    op.drop_column('manual_uploads', 'category')
    op.drop_column('manual_uploads', 'document_date')
    op.drop_column('manual_uploads', 'processing_error')
    op.drop_column('manual_uploads', 'original_filename')
    op.drop_column('manual_uploads', 'tags')
    op.alter_column('processed_items', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Total amount for the item (after discount, before tax)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_items', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Total amount for the item (after discount, before tax)')
    op.add_column('manual_uploads', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('original_filename', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('manual_uploads', sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('document_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('estimated_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('vendor_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manual_uploads', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('client_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('display_name', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('manual_uploads', sa.Column('processing_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('manual_uploads_source_id_fkey'), 'manual_uploads', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_manual_uploads_source_id'), 'manual_uploads', ['source_id'], unique=False)
    op.create_index(op.f('ix_manual_uploads_is_processed'), 'manual_uploads', ['is_processed'], unique=False)
    op.create_index(op.f('ix_manual_uploads_deleted_at'), 'manual_uploads', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_manual_uploads_user_status'), 'manual_uploads', ['user_id', 'processing_status'], unique=False)
    op.create_index(op.f('idx_manual_uploads_processed'), 'manual_uploads', ['is_processed', 'processed_at'], unique=False)
    # ### end Alembic commands ###
