"""Docment staging table added

Revision ID: 819ffcf3c06e
Revises: 2f2c5599db59
Create Date: 2025-12-06 23:15:35.657824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819ffcf3c06e'
down_revision: Union[str, None] = '2f2c5599db59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if enum type already exists, if not create it
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_type WHERE typname = 'processingstatus'"
    )).fetchone()
    
    if not result:
        # Create enum type if it doesn't exist
        op.execute("CREATE TYPE processingstatus AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_staging',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('manual_upload_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('upload_notes', sa.Text(), nullable=True),
    sa.Column('document_processing_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='documentprocessingstatustest'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manual_upload_id'], ['manual_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staging_priority_status', 'document_staging', ['priority', 'document_processing_status', 'created_at'], unique=False)
    op.create_index('idx_staging_status_created', 'document_staging', ['document_processing_status', 'created_at'], unique=False)
    op.create_index('idx_staging_user_status', 'document_staging', ['user_id', 'document_processing_status'], unique=False)
    op.create_index(op.f('ix_document_staging_attachment_id'), 'document_staging', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_document_staging_file_hash'), 'document_staging', ['file_hash'], unique=False)
    op.create_index(op.f('ix_document_staging_id'), 'document_staging', ['id'], unique=False)
    op.create_index(op.f('ix_document_staging_manual_upload_id'), 'document_staging', ['manual_upload_id'], unique=False)
    op.create_index(op.f('ix_document_staging_document_processing_status'), 'document_staging', ['document_processing_status'], unique=False)
    op.create_index(op.f('ix_document_staging_source_id'), 'document_staging', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_staging_source_type'), 'document_staging', ['source_type'], unique=False)
    op.create_index(op.f('ix_document_staging_user_id'), 'document_staging', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_staging_uuid'), 'document_staging', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_staging_uuid'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_user_id'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_source_type'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_source_id'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_document_processing_status'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_manual_upload_id'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_id'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_file_hash'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_attachment_id'), table_name='document_staging')
    op.drop_index('idx_staging_user_status', table_name='document_staging')
    op.drop_index('idx_staging_status_created', table_name='document_staging')
    op.drop_index('idx_staging_priority_status', table_name='document_staging')
    op.drop_table('document_staging')
    
    # Drop enum type if no other tables are using it
    op.execute("DROP TYPE IF EXISTS processingstatus CASCADE")
    # ### end Alembic commands ###
