"""Adding new column is_imported

Revision ID: 8f931ec84abf
Revises: 9583363a1433
Create Date: 2025-10-07 23:23:47.787940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f931ec84abf'
down_revision: Union[str, None] = '9583363a1433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_email_data', sa.Column('is_imported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_email_data', 'is_imported')
    # ### end Alembic commands ###
