"""fix: items table added

Revision ID: b1e9fbff4f5c
Revises: 000a46b32a43
Create Date: 2025-11-06 01:26:24.312514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1e9fbff4f5c'
down_revision: Union[str, None] = '000a46b32a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_email_items_id'), table_name='processed_email_items')
    op.drop_index(op.f('ix_processed_email_items_processed_email_id'), table_name='processed_email_items')
    op.drop_table('processed_email_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_email_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('processed_email_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Foreign key linking to processed_email_data (invoice-level record)'),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Name/description of the product or service'),
    sa.Column('item_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Optional product/service code or SKU'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Product or service category (if available)'),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Quantity of the product/service'),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Unit of measurement, e.g., pcs, kg, hr'),
    sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Rate per unit of the item'),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Discount applied on the item, if any'),
    sa.Column('tax_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Applicable tax percentage'),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Total amount for the item (after discount, before tax)'),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Raw extracted or extra data (for auditing or debugging)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['processed_email_id'], ['processed_email_data.id'], name=op.f('processed_email_items_processed_email_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_email_items_pkey'))
    )
    op.create_index(op.f('ix_processed_email_items_processed_email_id'), 'processed_email_items', ['processed_email_id'], unique=False)
    op.create_index(op.f('ix_processed_email_items_id'), 'processed_email_items', ['id'], unique=False)
    # ### end Alembic commands ###
