"""attachement id added to Attacement table

Revision ID: d8bd0ae69426
Revises: fd41e01e35b8
Create Date: 2025-09-07 11:02:55.800847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bd0ae69426'
down_revision: Union[str, None] = 'fd41e01e35b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('attachment_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'attachments', ['attachment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='unique')
    op.drop_column('attachments', 'attachment_id')
    # ### end Alembic commands ###
