"""updated the enum field for the document type

Revision ID: dd9209e3f112
Revises: 13c8fbceeffb
Create Date: 2025-09-28 12:20:50.048894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd9209e3f112'
down_revision: Union[str, None] = '13c8fbceeffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_email_data', 'document_type',
               existing_type=postgresql.ENUM('INVOICE', 'BILL', 'EMI', 'PAYMENT_RECEIPT', 'TAX_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OTHER', name='documenttype'),
               type_=sa.Enum('INVOICE', 'BILL', 'EMI', 'PAYMENT_RECEIPT', 'TAX_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OTHER', name='documenttype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processed_email_data', 'document_type',
               existing_type=sa.Enum('INVOICE', 'BILL', 'EMI', 'PAYMENT_RECEIPT', 'TAX_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OTHER', name='documenttype', native_enum=False),
               type_=postgresql.ENUM('INVOICE', 'BILL', 'EMI', 'PAYMENT_RECEIPT', 'TAX_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'OTHER', name='documenttype'),
               existing_nullable=False)
    # ### end Alembic commands ###
