"""source enum changed to string

Revision ID: f442502867b1
Revises: 38e9cf7026a7
Create Date: 2025-11-07 00:02:42.731558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f442502867b1'
down_revision: Union[str, None] = '38e9cf7026a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'type',
               existing_type=postgresql.ENUM('email', 'whatsapp', 'gdrive', name='sourcetype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('email', 'whatsapp', 'gdrive', name='sourcetype'),
               existing_nullable=False)
    # ### end Alembic commands ###
