"""attachment_id column removed from document_staging table

Revision ID: f9f899af0c00
Revises: 20b322d3a700
Create Date: 2025-12-17 16:37:37.615753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f899af0c00'
down_revision: Union[str, None] = '20b322d3a700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_staging', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_staging', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_index(op.f('ix_document_staging_attachment_id'), table_name='document_staging')
    op.drop_index(op.f('ix_document_staging_manual_upload_id'), table_name='document_staging')
    op.drop_constraint(op.f('document_staging_manual_upload_id_fkey'), 'document_staging', type_='foreignkey')
    op.drop_constraint(op.f('document_staging_attachment_id_fkey'), 'document_staging', type_='foreignkey')
    op.drop_column('document_staging', 'attachment_id')
    op.drop_column('document_staging', 'manual_upload_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_staging', sa.Column('manual_upload_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_staging', sa.Column('attachment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_staging_attachment_id_fkey'), 'document_staging', 'attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('document_staging_manual_upload_id_fkey'), 'document_staging', 'manual_uploads', ['manual_upload_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_document_staging_manual_upload_id'), 'document_staging', ['manual_upload_id'], unique=False)
    op.create_index(op.f('ix_document_staging_attachment_id'), 'document_staging', ['attachment_id'], unique=False)
    op.alter_column('document_staging', 's3_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('document_staging', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
