"""user table updated-1

Revision ID: fd41e01e35b8
Revises: 
Create Date: 2025-09-02 16:31:29.132892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd41e01e35b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
